import { Router } from 'express';
import { healthRouter } from './health.js';
import { authRouter } from './auth.js';
import { branchesRouter } from './branches.js';
import { usersRouter } from './users.js';
import { rolesRouter } from './roles.js';
import { permissionsRouter } from './permissions.js';
import { settingsRouter } from './settings.js';
import { sheetTypesRouter } from './sheetTypes.js';
import { sizeFamiliesRouter } from './sizeFamilies.js';
import { readyProductsRouter } from './readyProducts.js';
import { servicesRouter } from './services.js';
import { businessPartnersRouter } from './businessPartners.js';
import { partnerCategoriesRouter } from './partnerCategories.js';
import { partnerTagsRouter } from './partnerTags.js';
import { quotationsRouter } from './quotations.js';
import { ordersRouter } from './orders.js';
import { departmentsRouter } from './departments.js';
import { workflowTemplatesRouter } from './workflowTemplates.js';
import { workOrdersRouter } from './workOrders.js';
import { workflowInstancesRouter } from './workflowInstances.js';
import { treasuryEntriesRouter } from './treasuryEntries.js';
import { documentTemplatesRouter } from './documentTemplates.js';
import { inventoryItemsRouter } from './inventoryItems.js';
import { pricingReferenceRouter } from './pricingReference.js';
import { attachmentsRouter } from './attachments.js';
import { employeeAdvancesRouter } from './employeeAdvances.js';
import { attendanceRouter } from './attendance.js';
import { machinesRouter } from './machines.js';

export const apiRouter = Router();

// Unprefixed: infra/health-check convention (load balancers, Docker healthchecks).
apiRouter.use('/health', healthRouter);

const api = Router();
api.use('/auth', authRouter);
api.use('/branches', branchesRouter);
api.use('/users', usersRouter);
api.use('/roles', rolesRouter);
api.use('/permissions', permissionsRouter);
api.use('/settings', settingsRouter);
api.use('/sheet-types', sheetTypesRouter);
api.use('/size-families', sizeFamiliesRouter);
api.use('/ready-products', readyProductsRouter);
api.use('/services', servicesRouter);
api.use('/partners', businessPartnersRouter);
api.use('/partner-categories', partnerCategoriesRouter);
api.use('/partner-tags', partnerTagsRouter);
api.use('/quotations', quotationsRouter);
api.use('/orders', ordersRouter);
api.use('/departments', departmentsRouter);
api.use('/workflow-templates', workflowTemplatesRouter);
api.use('/work-orders', workOrdersRouter);
api.use('/workflow-instances', workflowInstancesRouter);
api.use('/treasury-entries', treasuryEntriesRouter);
api.use('/document-templates', documentTemplatesRouter);
api.use('/inventory-items', inventoryItemsRouter);
api.use('/pricing-reference', pricingReferenceRouter);
api.use('/attachments', attachmentsRouter);
api.use('/employee-advances', employeeAdvancesRouter);
api.use('/attendance', attendanceRouter);
api.use('/machines', machinesRouter);
apiRouter.use('/api', api);
